
general:
  startup: dat_extract.rb
  core: cui
  kcode: none


resource:
  version:
    file_version_number   : 1.5.0.17
    product_version_number: 1.5.0.17
    comments              : 固定されていない時間増分に対処(r17)
    company_name          : NSC
    legal_copyright       : Tanabe
    legal_trademarks      : Tanabe
    file_version          : Version 1.5.0
    product_version       : Version 1.5.0
    product_name          : DatExtract
    file_description      : Abaqusのdatより波形データを抽出しCSVで出力する．
    internal_name         : dat_extract.rb
    original_filename     : dat_extract.exe
    private_build         : RUBY_VERSION
    special_build         : RUBY_VERSION

