
general:
  startup: dat_extract.rb
  core: cui
  kcode: none


resource:
  version:
    file_version_number   : 1.5.0.18
    product_version_number: 1.5.0.18
    comments              : 要素のパース時エラーへの対応(r18)
    company_name          : NSC
    legal_copyright       : Tanabe
    legal_trademarks      : Tanabe
    file_version          : Version 1.5.0
    product_version       : Version 1.5.0
    product_name          : DatExtract
    file_description      : Abaqusのdatより波形データを抽出しCSVで出力する．
    internal_name         : dat_extract.rb
    original_filename     : dat_extract.exe
    private_build         : RUBY_VERSION
    special_build         : RUBY_VERSION

