require 'abaqus/element/b31'
require 'abaqus/element/b33'
require 'abaqus/element/mass'
require 'abaqus/element/s3'
require 'abaqus/element/s4'
require 'abaqus/element/s8'
require 'abaqus/element/c3d8'
